
CREATE TABLE CATEGORY (ID int8 GENERATED BY DEFAULT AS IDENTITY,
					   NAME VARCHAR(255) NOT NULL,
					   DESCRIPTION VARCHAR(255) NOT NULL,
					   PRIMARY KEY (ID));
					   
					   
CREATE TABLE ENTRY (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amount numeric(19,2),
    date date,
    description character varying(255),
    name character varying(255) ,
    paid boolean NOT NULL,
    type character varying(255),
    category_id int8,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id));

INSERT INTO category(name, description) VALUES ('Salário','Recebimento de Salário');
INSERT INTO category(name, description) VALUES ('Moradia','Fin. Caixa, Gás, Àgua, Energia, Internet, etc');
INSERT INTO category(name, description) VALUES ('Empréstimo','Empréstimo pessoal');
INSERT INTO category(name, description) VALUES ('Veículos ','Consorcio, Combustível, Manutenção, etc');
INSERT INTO category(name, description) VALUES ('Alimentação','Alimentação Mensal');
INSERT INTO category(name, description) VALUES ('Lazer','Cinema, Praia, etc');
INSERT INTO category(name, description) VALUES ('Outras','Creche');
INSERT INTO category(name, description) VALUES ('Cartão de Crédito','Fatura do Cartão de  Crédito');


INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (2,350.00,'2022-01-18','Financiamento da Caixa','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (5,50.00,'2022-01-10','Gás','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (4,60.00,'2022-01-10','Internet','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (3,332.19,'2022-01-10','Pagamento de Consocio ','True','expense',4);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (6,56.73,'2022-01-10','Água','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (7,200.00,'2022-01-10','Pagamento Energia','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (8,736.43,'2022-01-10','Fatura Cartão de Crédito','True','expense',8);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (9,327.90,'2022-01-15','Fatura do Cartão de Crédito','True','expense',8);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (10,130.08,'2022-01-10','Pagamento de Empréstimo','True','expense',3);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (11,184.08,'2022-01-10','Empréstimo Digio','True','expense',3);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (12,350.00,'2022-01-10','Creche','True','expense',7);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (13,350.00,'2022-02-18','Financiamento caixa ','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (14,329.29,'2022-02-10','Pagamento de consorcio','True','expense',4);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (15,60.00,'2022-02-10','Pagamento de Serviço de Internet','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (16,54.61,'2022-02-10','Pagamento Gás','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (17,77.80,'2022-02-10','Pagamento de água','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (18,179.47,'2022-02-10','Pagamento de Energia','True','expense',2);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (19,569.12,'2022-02-10','Pagamento Cartão de Credito BB','True','expense',8);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (20,751.67,'2022-02-15','Pagamento Cartão de credito Nu Bank','True','expense',8);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (21,184.08,'2022-02-07','Pagamento de Empréstimo Digio','True','expense',3);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (22,130.08,'2022-02-11','Pagamento Empréstimo Nu Bank','True','expense',3);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (23,350.00,'2022-02-10','Pagamento Creche','True','expense',7);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (24,2307.64,'2022-02-04','Recebimento de Salário','True','revenue',1);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (25,339.70,'2022-03-10','Pagamento Consócio Carro','False','expense',4);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (26,520.40,'2022-03-10','Pagamento Fatura Cartão BB','False','expense',8);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (27,607.42,'2022-03-15','Pagamento Fatura Cartão de Crédito Nubank','False','expense',8);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (28,130.08,'2022-03-11','Pagamento Empréstimo Nu Bank','False','expense',3);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (29,184.08,'2022-03-07','Pagamento Empréstimo Digio','False','expense',3);
INSERT INTO entry(id, amount, date, description, name, paid, type, category_id) VALUES (1,2548.01,'2022-01-07','Recebimento de Salário','True','revenue',1);
