
CREATE TABLE CATEGORY (ID int8 GENERATED BY DEFAULT AS IDENTITY,
					   NAME VARCHAR(255) NOT NULL,
					   DESCRIPTION VARCHAR(255) NOT NULL,
					   PRIMARY KEY (ID));
					   
					   
CREATE TABLE ENTRY (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amount numeric(19,2),
    date date,
    description VARCHAR(255),
    name VARCHAR(255) ,
    paid boolean NOT NULL,
    type VARCHAR(255),
    category_id int8,
    PRIMARY KEY (id));
	alter table if exists ENTRY add constraint FK23yhb6qop0f6hnb72hcorm3cv foreign key ( category_id ) references CATEGORY;

INSERT INTO category(name, description) VALUES ('Salário','Recebimento de Salário');
INSERT INTO category(name, description) VALUES ('Moradia','Fin. Caixa, Gás, Àgua, Energia, Internet, etc');
INSERT INTO category(name, description) VALUES ('Empréstimo','Empréstimo pessoal');
INSERT INTO category(name, description) VALUES ('Veículos ','Consorcio, Combustível, Manutenção, etc');
INSERT INTO category(name, description) VALUES ('Alimentação','Alimentação Mensal');
INSERT INTO category(name, description) VALUES ('Lazer','Cinema, Praia, etc');
INSERT INTO category(name, description) VALUES ('Outras','Creche');
INSERT INTO category(name, description) VALUES ('Cartão de Crédito','Fatura do Cartão de  Crédito');


INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (350.00,'2022-01-18','Financiamento da Caixa','Fin. Caixa','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (50.00,'2022-01-10','Gás','Gás','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (60.00,'2022-01-10','Internet','Internet','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (332.19,'2022-01-10','Pagamento de Consocio ','Pagamento de Consocio ','True','expense',4);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (56.73,'2022-01-10','Água','Água','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (200.00,'2022-01-10','Pagamento Energia','Energia','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (736.43,'2022-01-10','Fatura Cartão de Crédito','Cart. de Créd. BB','True','expense',8);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (327.90,'2022-01-15','Fatura do Cartão de Crédito','Cart de Créd. NU','True','expense',8);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (130.08,'2022-01-10','Pagamento de Empréstimo','Empréstimo NUBANK','True','expense',3);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (184.08,'2022-01-10','Empréstimo Digio','Empréstimo Digio','True','expense',3);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (350.00,'2022-01-10','Creche','Creche','True','expense',7);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (350.00,'2022-02-18','Financiamento caixa ','Fin. Caixa','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (329.29,'2022-02-10','Pagamento de consorcio','Consocio Carro','True','expense',4);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (60.00,'2022-02-10','Pagamento de Serviço de Internet','Internet','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (54.61,'2022-02-10','Pagamento Gás','Gás','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (77.80,'2022-02-10','Pagamento de água','Pagamento de água','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (179.47,'2022-02-10','Pagamento de Energia','Pagamento de Energia','True','expense',2);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (569.12,'2022-02-10','Pagamento Cartão de Credito BB','Cartão de Credito BB','True','expense',8);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (751.67,'2022-02-15','Pagamento Cartão de credito Nu Bank','Cartão de credito Nu Bank','True','expense',8);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (184.08,'2022-02-07','Pagamento de Empréstimo Digio','Empréstimo Digio','True','expense',3);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (130.08,'2022-02-11','Pagamento Empréstimo Nu Bank','Empréstimo Nu Bank','True','expense',3);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (350.00,'2022-02-10','Pagamento Creche','Creche','True','expense',7);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (2307.64,'2022-02-04','Recebimento de Salário','Recebimento de Salário','True','revenue',1);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (339.70,'2022-03-10','Pagamento Consócio Carro','Consócio Carro','False','expense',4);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (520.40,'2022-03-10','Pagamento Fatura Cartão BB','Fatura Cartão BB','False','expense',8);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (607.42,'2022-03-15','Pagamento Fatura Cartão de Crédito Nubank','Fatura Cartão de Crédito Nubank','False','expense',8);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (130.08,'2022-03-11','Pagamento Empréstimo Nu Bank','Empréstimo Nu Bank','False','expense',3);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (184.08,'2022-03-07','Pagamento Empréstimo Digio','Empréstimo Digio','False','expense',3);
INSERT INTO entry(amount, date, description, name, paid, type, category_id) VALUES  (2548.01,'2022-01-07','Recebimento de Salário','Recebimento de Salário','True','revenue',1);
